FROM ubuntu:trusty

MAINTAINER Roeland Jago Douma <roeland@famdouma.nl>

RUN apt-get update && \
    apt-get install -y wget libsqlite3-dev libssl-dev cmake git \
        software-properties-common build-essential mesa-common-dev \
        fuse rsync curl libssl-dev

RUN add-apt-repository -y ppa:beineri/opt-qt595-trusty && \
    apt-get update && \
    apt-get install -y qt59base qt59tools qt59webengine qt59svg

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y gcc-7 g++-7

RUN add-apt-repository -y ppa:george-edison55/cmake-3.x && \
    apt-get update && \
    apt-get install -y cmake
