FROM ubuntu:xenial

MAINTAINER Roeland Jago Douma <roeland@famdouma.nl>

RUN apt-get update && \
    apt-get install -y wget libsqlite3-dev libssl-dev cmake git \
        software-properties-common build-essential mesa-common-dev \
        fuse rsync curl

RUN add-apt-repository -y ppa:beineri/opt-qt593-xenial && \
    apt-get update && \
    apt-get install -y qt59base qt59tools qt59webengine

