FROM ubuntu:24.04

MAINTAINER Morris Jobke <hey@morrisjobke.de>

# Install python
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -q -y --no-install-recommends \
        gawk \
        gettext \
        git \
        gnupg \
        make \
        curl \
        openssh-client \
        ca-certificates \
        php8.3-cli \
        php8.3-xml \
        jq \
    && apt-get clean

#        qttools5-dev-tools \

RUN update-ca-certificates

# Install Transifex client
RUN cd /root
RUN curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash

ENV PATH=${PATH}:/

RUN mkdir -p /app

ADD temp/gitconfig /root/.gitconfig
ADD temp/known_hosts /root/.ssh/known_hosts
ADD temp/translationtool.phar /translationtool.phar
ADD temp/validateTranslationFiles.sh /validateTranslationFiles.sh
ADD handleAppTranslations.sh /handleTranslations.sh

WORKDIR /app

ENTRYPOINT ["/handleTranslations.sh"]
