FROM almalinux:8.10

MAINTAINER Desktop Team <desktop@nextcloud.com>

RUN dnf update -y && \
    dnf install -y epel-release && \
    dnf config-manager --set-enabled powertools && \
    dnf update -y && \
    dnf install -y \
        xz \
        gcc-toolset-14 \
        gcc-toolset-14-libatomic-devel \
        git-core \
        patch \
        python3.11 \
        python3.11-pip \
        at-spi2-atk-devel \
        mesa-vulkan-drivers \
        vulkan-headers \
        wayland-devel \
        mesa-libGL-devel \
        libX11-devel \
        libX11-xcb \
        libxcb-devel \
        libxkbcommon-devel \
        libxkbcommon-x11 \
        libXi-devel \
        libXcomposite-devel \
        libXcursor-devel \
        libXrandr-devel \
        libXtst-devel \
        xcb-util-devel \
        xcb-util-cursor \
        xcb-util-cursor-devel \
        xcb-util-keysyms \
        xcb-util-keysyms-devel \
        xcb-util-renderutil \
        xcb-util-renderutil-devel \
        xcb-util-wm \
        xcb-util-wm-devel \
        xcb-util-image \
        xcb-util-image-devel \
        libxkbcommon-x11-devel \
        xorg-x11-util-macros \
        wget \
        inkscape \
        file

###########################################################################

# Install craftmaster
RUN \
    cd /root && \
    git clone https://invent.kde.org/packaging/craftmaster.git \
    ;

ADD craftmaster-34.0-cache.ini /root/craftmaster.ini

# Install binary dependencies
RUN \
    scl run gcc-toolset-14 -- PKG_CONFIG_PATH=/usr/lib64/pkgconfig/:/usr/share/pkgconfig python3.11 /root/craftmaster/CraftMaster.py --config /root/craftmaster.ini --target linux-gcc-x86_64 -c --add-blueprint-repository "https://github.com/nextcloud/craft-blueprints-kde.git|stable-34.0|" && \
    scl run gcc-toolset-14 -- PKG_CONFIG_PATH=/usr/lib64/pkgconfig/:/usr/share/pkgconfig python3.11 /root/craftmaster/CraftMaster.py --config /root/craftmaster.ini --target linux-gcc-x86_64 -c --add-blueprint-repository "https://github.com/nextcloud/craft-blueprints-nextcloud.git|stable-34.0|" && \
    scl run gcc-toolset-14 -- PKG_CONFIG_PATH=/usr/lib64/pkgconfig/:/usr/share/pkgconfig python3.11 /root/craftmaster/CraftMaster.py --config /root/craftmaster.ini --target linux-gcc-x86_64 -c craft && \
    scl run gcc-toolset-14 -- PKG_CONFIG_PATH=/usr/lib64/pkgconfig/:/usr/share/pkgconfig python3.11 /root/craftmaster/CraftMaster.py --config /root/craftmaster.ini --target linux-gcc-x86_64 -c --install-deps nextcloud-client && \
    rm -rf /root/linux-gcc-x86_64/build \
    ;
