FROM mhart/alpine-node:10.16.3
# Sources at https://github.com/mhart/alpine-node
# Version 10.16.3 contains npm 6.12.0, yarn 1.19.1

MAINTAINER Joachim Bauch <mail@joachim-bauch.de>

RUN npm install -g stylelint@11.0.0
