FROM ghcr.io/nextcloud/continuous-integration-translations:latest

LABEL org.opencontainers.image.authors="Tobias Kaminsky <tobias.kaminsky@nextcloud.com>"

ADD handleSwiftNextcloudUITranslations.sh /handleTranslations.sh
