FROM nextcloudci/translations:translations-19

MAINTAINER Morris Jobke <hey@morrisjobke.de>

ADD handleChangelogServerTranslations.sh /handleTranslations.sh
ADD translationtool-whatsnew/ /translationtool

