FROM ghcr.io/nextcloud/continuous-integration-translations:latest

LABEL org.opencontainers.image.authors="Joas Schilling <joas.schilling@nextcloud.com>"

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -q -y --no-install-recommends \
        php7.4-dom \
    && apt-get clean

ADD handleChangelogServerTranslations.sh /handleTranslations.sh
ADD translationtool-whatsnew/ /translationtool

