FROM ghcr.io/nextcloud/continuous-integration-translations:latest

LABEL org.opencontainers.image.authors="Tobias Kaminsky <tobias.kaminsky@nextcloud.com>"

# Install python
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -q -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-wheel \
    && apt-get clean

ADD handlePlainTranslations.sh /handleTranslations.sh
