FROM nextcloudci/translations:translations-29

MAINTAINER Morris Jobke <hey@morrisjobke.de>

ADD handleChangelogServerTranslations.sh /handleTranslations.sh
ADD translationtool-whatsnew/ /translationtool

