FROM ghcr.io/nextcloud/continuous-integration-translations:latest

LABEL org.opencontainers.image.authors="Joas Schilling <joas.schilling@nextcloud.com>"

ADD handleiOSTranslations.sh /handleTranslations.sh
