FROM ghcr.io/nextcloud/continuous-integration-translations:latest

LABEL org.opencontainers.image.authors="Joas Schilling <joas.schilling@nextcloud.com>"

# Install python
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -q -y --no-install-recommends \
        build-essential \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        python3-setuptools \
        python3-wheel \
    && apt-get clean

# Add sym link for python
RUN ln -s /usr/bin/python3 /usr/bin/python

ADD handleAppstoreTranslations.sh /handleTranslations.sh
