FROM ghcr.io/nextcloud/continuous-integration-translations:latest

LABEL org.opencontainers.image.authors="Joas Schilling <joas.schilling@nextcloud.com>"

ADD handleTranslations.sh /handleTranslations.sh

RUN apt update && apt install -y wget

RUN cd /root

RUN wget http://archive.ubuntu.com/ubuntu/pool/main/g/gettext/gettext_0.23.1-1_amd64.deb -O gettext.deb \
    && apt install -y /root/gettext.deb

RUN gettext --version
