FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pil \
    python3-pip texlive-fonts-recommended latexmk \
    texlive-latex-extra texlive-latex-recommended make php-cli php-xml composer \
    nodejs npm libgbm1 libasound2 wget

