name: Docker Publish

on:
  workflow_dispatch:
    inputs:
      folderPath:
        description: "Path to the folder"
        required: true
        default: 'webdav-apache-php7.3'
      dockerFile:
        description: "Optional relative (from folder) path to Dockerfile. Default is $folder/Dockerfile"
        required: false
        default: 'Dockerfile'
      suffix:
        description: "Option suffix to image name (e.g. `-documentation`)"
        required: false
      tagName:
        description: "Tag name"
        required: true
        default: 'latest'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    name: Push Docker image ${{ github.event.inputs.folderPath }}${{ github.event.inputs.suffix }}:${{ github.event.inputs.tagName }} to GitHub Packages

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check actor permission
        uses: skjnldsv/check-actor-permission@69e92a3c4711150929bca9fcf34448c5bf5526e7 # v3.0
        with:
          require: admin

      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          # https://github.com/tonistiigi/binfmt/issues/240
          # https://github.com/docker/buildx/issues/1170
          image: tonistiigi/binfmt:qemu-v7.0.0-28
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: ${{ startsWith(github.event.inputs.folderPath, 'client') && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          push: true
          context: ${{ github.event.inputs.folderPath }}
          file: '${{ github.event.inputs.folderPath }}/${{ github.event.inputs.dockerFile }}'
          tags: |
            ghcr.io/nextcloud/continuous-integration-${{ github.event.inputs.folderPath }}${{ github.event.inputs.suffix }}:${{ github.event.inputs.tagName }}
