name: Docker Publish

on:
  workflow_dispatch:
    inputs:
      folderPath:
        description: "Path to the folder"
        required: true
        default: 'webdav-apache-php7.3'
      dockerFile:
        description: "Optional relative (from folder) path to Dockerfile. Default is $folder/Dockerfile"
        required: false
        default: 'Dockerfile'
      suffix:
        description: "Option suffix to image name (e.g. `-documentation`)"
        required: false
      tagName:
        description: "Tag name"
        required: true
        default: 'latest'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    name: Push Docker image ${{ github.event.inputs.folderPath }}${{ github.event.inputs.suffix }}:${{ github.event.inputs.tagName }} to GitHub Packages

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check actor permission
        uses: skjnldsv/check-actor-permission@69e92a3c4711150929bca9fcf34448c5bf5526e7 # v3.0
        with:
          require: admin

      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          push: true
          context: ${{ github.event.inputs.folderPath }}
          file: '${{ github.event.inputs.folderPath }}/${{ github.event.inputs.dockerFile }}'
          tags: |
            ghcr.io/nextcloud/continuous-integration-${{ github.event.inputs.folderPath }}${{ github.event.inputs.suffix }}:${{ github.event.inputs.tagName }}
