name: Create Psalm Container

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    name: Create Psalm Container

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        run: |
          git clone https://github.com/psalm/psalm-github-actions.git
      
      - name: Modify the Dockerfile
        run: |
          set -x
          sed -i 's|FROM php:7.4-alpine|FROM php:7.0-alpine|' "psalm-github-actions/Dockerfile"
          sed -i 's|COPY --from=composer:2|COPY --from=composer:1|' "psalm-github-actions/Dockerfile"

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: 'psalm-github-actions'
          file: 'psalm-github-actions/Dockerfile'
          tags: |
            ghcr.io/nextcloud/docker-ci/psalm:php7.0
